### ISSUE TITLE
Panic on creating new wallet

### ISSUE THREAD

**Issue by Varunram** [algorand/go-algorand-sdk#23]
I'm trying out the Algorand go sdk and get this when I try to create a new wallet on a private network:
```
./goal wallet new testwallet -d private/
Please choose a password for wallet 'testwallet':
Please confirm the password:
Creating wallet...
Created wallet 'testwallet'
Your new wallet has a backup phrase that can be used for recovery.
Keeping this backup phrase safe is extremely important.
Would you like to see it now? (Y/n): Y
Your backup phrase is printed below.
Keep this information safe -- never share it with anyone!

parrot rifle bean into elephant poet rough erosion turn prevent file capital twelve cabin dizzy leaf mercy agree tag quantum clock paddle bright able taste
ERRO[0008] [Stack] goroutine 1 [running]:
runtime/debug.Stack(0xc0000c82d0, 0xc000010490, 0xc0003361e0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/debug/stack.go:24 +0x9d
github.com/algorand/go-algorand/logging.logger.Error(0xc0000c82d0, 0xc000010490, 0xc000330240, 0x1, 0x1)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/logging/log.go:216 +0x48
main.(*AccountsList).dumpList(0xc0002565c0)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/accountsList.go:189 +0x1a6
main.(*AccountsList).setDefaultWalletID(...)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/accountsList.go:82
main.glob..func58(0x572b100, 0xc0002da540, 0x1, 0x3)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/wallet.go:183 +0x7e9
github.com/algorand/go-algorand/vendor/github.com/spf13/cobra.(*Command).execute(0x572b100, 0xc0002da4b0, 0x3, 0x3, 0x572b100, 0xc0002da4b0)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/algorand/go-algorand/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x572eec0, 0x4d107f6, 0x7, 0x4d0c83c)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/vendor/github.com/spf13/cobra/command.go:852 +0x2c0
github.com/algorand/go-algorand/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/travis/gopath/src/github.com/algorand/go-algorand/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/Users/travis/gopath/src/github.com/algorand/go-algorand/cmd/goal/commands.go:133 +0x97
  file=accountsList.go function="main.(*AccountsList).dumpList" line=189
ERRO[0008] open private/private-v38/accountList.json: no such file or directory  file=accountsList.go function="main.(*AccountsList).dumpList" line=189
open private/private-v38/accountList.json: no such file or directory
```

Any reason why?

**Comment by JasonWeathersby** [comment]
You are using the goal command line. I just tried this and it worked fine. I put it in a shell script:

#!/bin/bash
set -e

echo "### Creating private network"
goal network create -n tn50e -t networktemplate.json -r test
echo

echo "### Starting private network"
goal network start -r test
echo

echo "### Checking node status"
goal network status -r test

echo "### Importing root keys"
NODEKEY=$(goal account list -d test/Node |  awk '{print $2}')
PRIMKEY=$(goal account list -d test/Primary | awk '{print $2}')

echo "Imported ${NODEKEY}"
echo "Imported ${PRIMKEY}"
echo

read -p "Press enter to create a wallet"
goal wallet new MyWallet -d ~/net1/Primary


echo "### Stop private network"
goal network stop -r test
goal network delete -r test

**Comment by Varunram** [comment]
yeah, this works. Also  `./goal wallet new testwallet -d private/` panics whereas `./goal wallet new testwallet -d private/Primary` doesn't. So I guess  somewhere in the codebase it checks for user directories and weirdly enough panics when it really shouldn't.

**Comment by JasonWeathersby** [comment]
You are correct. It is an error situation.

**Comment by rotemh** [comment]
@JasonWeathersby let's move it to the proper repo. It doesn't belong here. Closing this issue.
